# LOGISTIC REGRESSION

In [84]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt

In [106]:
url="https://raw.githubusercontent.com/toukirnaim08/Rainfall-Prediction-Australian-Weather-Dataset/master/weatherAUS.csv"
df=pd.read_csv(url)

In [108]:
df['Date']=df['Date'] + "-2021"

In [105]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01-2021,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02-2021,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03-2021,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04-2021,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05-2021,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No

In [109]:
df['RainToday']=df['RainToday'].apply(lambda x:1 if x == "Yes" else 0)
df['RainTomorrow']=df['RainTomorrow'].apply(lambda x:1 if x == "Yes" else 0)

In [111]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.shape

(142193, 24)

In [112]:
df.WindGustDir = le.fit_transform(df.WindGustDir)

In [113]:
df.WindDir3pm = le.fit_transform(df.WindDir3pm)

In [114]:
df.WindDir9am = le.fit_transform(df.WindDir9am)

In [115]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
count,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,142193.000000,132923.000000,142193.000000,142193.000000,140845.000000,...,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,142193.000000,142193.000000,142193.000000
mean,12.186400,23.226784,2.349974,5.469824,7.624853,8.255885,39.984292,7.915755,7.974471,14.001988,...,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,0.221213,2.360682,0.224181
std,6.403283,7.117618,8.465173,4.188537,3.781525,4.953096,13.588801,4.911307,4.731493,8.893337,...,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,0.415065,8.477969,0.417043
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,...,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,0.000000,0.000000,0.000000
25%,7.600000,17.900000,0.000000,2.600000,4.900000,4.000000,31.000000,3.000000,4.000000,7.000000,...,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,0.000000,0.000000,0.000000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,9.000000,39.000000,8.000000,8.000000,13.000000,...,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,0.000000,0.000000,0.000000
75%,16.800000,28.200000,0.800000,7.400000,10.600000,13.000000,48.000000,12.000000,12.000000,19.000000,...,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,0.000000,0.800000,0.000000
max,33.900000,48.100000,371.000000,145.000000,14.500000,16.000000,135.000000,16.000000,16.000000,130.000000,...,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,1.000000,371.000000,1.000000

In [123]:
df=df.dropna()

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58090 entries, 5939 to 139112
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           58090 non-null  object
 1   Location       58090 non-null  object
 2   MinTemp        58090 non-null  float64
 3   MaxTemp        58090 non-null  float64
 4   Rainfall       58090 non-null  float64
 5   Evaporation    58090 non-null  float64
 6   Sunshine       58090 non-null  float64
 7   WindGustDir    58090 non-null  int32
 8   WindGustSpeed  58090 non-null  float64
 9   WindDir9am     58090 non-null  int32
 10  WindDir3pm     58090 non-null  int32
 11  WindSpeed9am   58090 non-null  float64
 12  WindSpeed3pm   58090 non-null  float64
 13  Humidity9am    58090 non-null  float64
 14  Humidity3pm    58090 non-null  float64
 15  Pressure9am    58090 non-null  float64
 16  Pressure3pm    58090 non-null  float64
 17  Cloud9am       58090 non-null  float64
 18  Cloud3pm       58090 non-null  float64
 19  Temp9am        58090 non-null  float64
 20  Temp3pm        58090 non-null  float64
 21  RainToday      58090 non-null  int64
 22  RISK_MM        58090 non-null  float64
 23  RainTomorrow   58090 non-null  int64
dtypes: float64(17), int32(3), int64(2), object(2)
memory usage: 10.4+ MB

In [125]:
from sklearn.model_selection import train_test_split
x = df.drop(['Date','Location','RainTomorrow'],axis=1)
y = df['RainTomorrow']

In [126]:
train_x , train_y ,test_x , test_y = train_test_split(x,y , test_size = 0.2,random_state=42)

In [127]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_x , test_x)

C:\Users\Rand Rothstein\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [128]:
predict = model.predict(train_y)

In [129]:
from sklearn.metrics import accuracy_score
accuracy_score(predict , test_y)

0.9833017731106903

In [133]:
import pandas as pd
url='https://raw.githubusercontent.com/dataquestio/project-walkthroughs/master/football_matches/matches.csv'
matches=pd.read_csv(url)

In [131]:
pred = pd.DataFrame(predict,columns=['weather'])

In [132]:
matches = pd.concat([matches,pred],axis=1)

In [136]:
matches.head()
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1389 entries, 0 to 1388
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    1389 non-null   int64
 1   date          1389 non-null   object
 2   time          1389 non-null   object
 3   comp          1389 non-null   object
 4   round         1389 non-null   object
 5   day           1389 non-null   object
 6   venue         1389 non-null   object
 7   result        1389 non-null   object
 8   gf            1389 non-null   float64
 9   ga            1389 non-null   float64
 10  opponent      1389 non-null   object
 11  xg            1389 non-null   float64
 12  xga           1389 non-null   float64
 13  poss          1389 non-null   float64
 14  attendance    693 non-null    float64
 15  captain       1389 non-null   object
 16  formation     1389 non-null   object
 17  referee       1389 non-null   object
 18  match report  1389 non-null   object
 19  notes         0 non-null      float64
 20  sh            1389 non-null   float64
 21  sot           1389 non-null   float64
 22  dist          1388 non-null   float64
 23  fk            1389 non-null   float64
 24  pk            1389 non-null   float64
 25  pkatt         1389 non-null   float64
 26  season        1389 non-null   int64
 27  team          1389 non-null   object
dtypes: float64(13), int64(2), object(13)
memory usage: 304.0+ KB

In [44]:
matches["team"].value_counts()

Newcastle United            72
West Ham United             72
Southampton                 72
Brighton and Hove Albion    72
Manchester United           72
Tottenham Hotspur           71
Leeds United                71
Manchester City             71
Wolverhampton Wanderers     71
Arsenal                     71
Crystal Palace              71
Burnley                     71
Leicester City              70
Chelsea                     70
Aston Villa                 70
Everton                     70
Sheffield United            38
Liverpool                   38
West Bromwich Albion        38
Fulham                      38
Brentford                   34
Norwich City                33
Watford                     33
Name: team, dtype: int64

In [137]:
matches[matches["team"] == "Liverpool"].sort_values("date")

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
705,1,2020-09-12,17:30,Premier League,Matchweek 1,Sat,Home,W,4.0,3.0,...,Match Report,NaN,20.0,4.0,17.0,0.0,2.0,2.0,2021,Liverpool
706,2,2020-09-20,16:30,Premier League,Matchweek 2,Sun,Away,W,2.0,0.0,...,Match Report,NaN,17.0,5.0,17.7,1.0,0.0,0.0,2021,Liverpool
707,4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Home,W,3.0,1.0,...,Match Report,NaN,21.0,9.0,16.8,0.0,0.0,0.0,2021,Liverpool
708,6,2020-10-04,19:15,Premier League,Matchweek 4,Sun,Away,L,2.0,7.0,...,Match Report,NaN,14.0,8.0,15.8,1.0,0.0,0.0,2021,Liverpool
709,7,2020-10-17,12:30,Premier League,Matchweek 5,Sat,Away,D,2.0,2.0,...,Match Report,NaN,22.0,8.0,15.0,1.0,0.0,0.0,2021,Liverpool
710,9,2020-10-24,20:00,Premier League,Matchweek 6,Sat,Home,W,2.0,1.0,...,Match Report,NaN,17.0,5.0,18.2,1.0,0.0,0.0,2021,Liverpool
711,11,2020-10-31,17:30,Premier League,Matchweek 7,Sat,Home,W,2.0,1.0,...,Match Report,NaN,8.0,2.0,18.6,1.0,1.0,1.0,2021,Liverpool
712,13,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Away,D,1.0,1.0,...,Match Report,NaN,9.0,2.0,21.5,0.0,1.0,1.0,2021,Liverpool
713,14,2020-11-22,19:15,Premier League,Matchweek 9,Sun,Home,W,3.0,0.0,...,Match Report,NaN,24.0,12.0,11.9,0.0,0.0,0.0,2021,Liverpool
714,16,2020-11-28,12:30,Premier League,Matchweek 10,Sat,Away,D,1.0,1.0,...,Match Report,NaN,6.0,2.0,20.9,0.0,0.0,0.0,2021,Liverpool
715,18,2020-12-06,19:15,Premier League,Matchweek 11,Sun,Home,W,4.0,0.0,...,Match Report,NaN,11.0,6.0,16.6,1.0,0.0,0.0,2021,Liverpool
716,20,2020-12-13,16:30,Premier League,Matchweek 12,Sun,Away,D,1.0,1.0,...,Match Report,NaN,11.0,5.0,20.0,1.0,1.0,1.0,2021,Liverpool
717,21,2020-12-16,20:00,Premier League,Matchweek 13,Wed,Home,W,2.0,1.0,...,Match Report,NaN,17.0,11.0,15.5,0.0,0.0,0.0,2021,Liverpool
718,22,2020-12-19,12:30,Premier League,Matchweek 14,Sat,Away,W,7.0,0.0,...,Match Report,NaN,14.0,7.0,13.2,1.0,0.0,0.0,2021,Liverpool
719,23,2020-12-27,16:30,Premier League,Matchweek 15,Sun,Home,D,1.0,1.0,...,Match Report,NaN,17.0,2.0,17.8,2.0,0.0,0.0,2021,Liverpool
720,24,2020-12-30,20:00,Premier League,Matchweek 16,Wed,Away,D,0.0,0.0,...,Match Report,NaN,11.0,4.0,16.7,0.0,0.0,0.0,2021,Liverpool
721,25,2021-01-04,20:00,Premier League,Matchweek 17,Mon,Away,L,0.0,1.0,...,Match Report,NaN,17.0,1.0,14.3,0.0,0.0,0.0,2021,Liverpool
722,27,2021-01-17,16:30,Premier League,Matchweek 19,Sun,Home,D,0.0,0.0,...,Match Report,NaN,17.0,3.0,17.1,0.0,0.0,0.0,2021,Liverpool
723,28,2021-01-21,20:00,Premier League,Matchweek 18,Thu,Home,L,0.0,1.0,...,Match Report,NaN,27.0,6.0,17.3,0.0,0.0,0.0,2021,Liverpool
724,30,2021-01-28,20:00,Premier League,Matchweek 20,Thu,Away,W,3.0,1.0,...,Match Report,NaN,14.0,7.0,14.7,0.0,0.0,0.0,2021,Liverpool
725,31,2021-01-31,16:30,Premier League,Matchweek 21,Sun,Away,W,3.0,1.0,...,Match Report,NaN,14.0,5.0,15.3,0.0,0.0,0.0,2021,Liverpool
726,32,2021-02-03,20:15,Premier League,Matchweek 22,Wed,Home,L,0.0,1.0,...,Match Report,NaN,11.0,0.0,19.9,0.0,0.0,0.0,2021,Liverpool
727,33,2021-02-07,16:30,Premier League,Matchweek 23,Sun,Home,L,1.0,4.0,...,Match Report,NaN,7.0,2.0,17.9,1.0,1.0,1.0,2021,Liverpool
728,34,2021-02-13,12:30,Premier League,Matchweek 24,Sat,Away,L,1.0,3.0,...,Match Report,NaN,15.0,4.0,15.4,2.0,0.0,0.0,2021,Liverpool
729,36,2021-02-20,17:30,Premier League,Matchweek 25,Sat,Home,L,0.0,2.0,...,Match Report,NaN,16.0,6.0,15.9,1.0,0.0,0.0,2021,Liverpool
730,37,2021-02-28,19:15,Premier League,Matchweek 26,Sun,Away,W,2.0,0.0,...,Match Report,NaN,15.0,8.0,14.2,0.0,0.0,0.0,2021,Liverpool
731,38,2021-03-04,20:15,Premier League,Matchweek 29,Thu,Home,L,0.0,1.0,...,Match Report,NaN,7.0,1.0,18.4,0.0,0.0,0.0,2021,Liverpool
732,39,2021-03-07,14:00,Premier League,Matchweek 27,Sun,Home,L,0.0,1.0,...,Match Report,NaN,16.0,3.0,17.0,1.0,0.0,0.0,2021,Liverpool
733,41,2021-03-15,20:00,Premier League,Matchweek 28,Mon,Away,W,1.0,0.0,...,Match Report,NaN,12.0,4.0,15.9,0.0,0.0,0.0,2021,Liverpool
734,42,2021-04-03,20:00,Premier League,Matchweek 30,Sat,Away,W,3.0,0.0,...,Match Report,NaN,16.0,7.0,17.0,0.0,0.0,0.0,2021,Liverpool
735,44,2021-04-10,15:00,Premier League,Matchweek 31,Sat,Home,W,2.0,1.0,...,Match Report,NaN,23.0,8.0,16.7,1.0,0.0,0.0,2021,Liverpool
736,46,2021-04-19,20:00,Premier League,Matchweek 32,Mon,Away,D,1.0,1.0,...,Match Report,NaN,17.0,7.0,15.7,0.0,0.0,0.0,2021,Liverpool
737,47,2021-04-24,12:30,Premier League,Matchweek 33,Sat,Home,D,1.0,1.0,...,Match Report,NaN,21.0,9.0,17.0,1.0,0.0,0.0,2021,Liverpool
738,48,2021-05-08,20:15,Premier League,Matchweek 35,Sat,Home,W,2.0,0.0,...,Match Report,NaN,14.0,6.0,12.4,0.0,0.0,0.0,2021,Liverpool
739,49,2021-05-13,20:15,Premier League,Matchweek 34,Thu,Away,W,4.0,2.0,...,Match Report,NaN,17.0,8.0,14.9,0.0,0.0,0.0,2021,Liverpool
740,50,2021-05-16,16:30,Premier League,Matchweek 36,Sun,Away,W,2.0,1.0,...,Match Report,NaN,26.0,6.0,16.9,1.0,0.0,0.0,2021,Liverpool
741,51,2021-05-19,20:15,Premier League,Matchweek 37,Wed,Away,W,3.0,0.0,...,Match Report,NaN,20.0,3.0,15.5,1.0,0.0,0.0,2021,Liverpool
742,52,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,2.0,0.0,...,Match Report,NaN,19.0,5.0,14.2,1.0,0.0,0.0,2021,Liverpool

In [46]:
matches["round"].value_counts()

Matchweek 15    39
Matchweek 4     39
Matchweek 2     39
Matchweek 5     39
Matchweek 26    39
Matchweek 29    39
Matchweek 31    39
Matchweek 13    39
Matchweek 10    39
Matchweek 32    39
Matchweek 24    39
Matchweek 34    39
Matchweek 6     39
Matchweek 28    39
Matchweek 25    39
Matchweek 12    39
Matchweek 1     39
Matchweek 16    39
Matchweek 7     39
Matchweek 19    39
Matchweek 23    39
Matchweek 11    39
Matchweek 14    39
Matchweek 20    39
Matchweek 3     39
Matchweek 8     39
Matchweek 9     39
Matchweek 17    39
Matchweek 22    37
Matchweek 18    37
Matchweek 27    37
Matchweek 30    37
Matchweek 21    37
Matchweek 33    32
Matchweek 36    20
Matchweek 37    20
Matchweek 35    20
Matchweek 38    20
Name: round, dtype: int64

In [47]:
del matches["notes"]
del matches["comp"]

In [48]:
matches["target"] = (matches["result"] == "W").astype("int")

In [49]:
matches["date"] = pd.to_datetime(matches["date"])

In [50]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes
matches["opp_code"] = matches["opponent"].astype("category").cat.codes
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")
matches["day_code"] = matches["date"].dt.dayofweek

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)
train = matches[matches["date"] < '2022-01-01']
test = matches[matches["date"] > '2022-01-01']
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [53]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [54]:
preds = rf.predict(test[predictors])

In [55]:
from sklearn.metrics import accuracy_score

In [56]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [57]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          141  31
1           76  28

In [58]:
error = accuracy_score(test["target"], preds)
print(error)

0.6123188405797102

In [62]:
grouped_matches = matches.groupby("team")

In [63]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [65]:
group

,Unnamed: 0,date,time,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
629,0,2020-09-21,20:15,Matchweek 2,Mon,Away,W,3.0,1.0,Wolves,...,2.0,1.0,1.0,2021,Manchester City,1,0,22,20,0
630,2,2020-09-27,16:30,Matchweek 3,Sun,Home,L,2.0,5.0,Leicester City,...,1.0,0.0,0.0,2021,Manchester City,0,1,10,16,6
631,4,2020-10-03,17:30,Matchweek 4,Sat,Away,D,1.0,1.0,Leeds United,...,1.0,0.0,0.0,2021,Manchester City,0,0,9,17,5
632,5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,...,0.0,0.0,0.0,2021,Manchester City,1,1,0,17,5
633,7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,...,1.0,0.0,0.0,2021,Manchester City,0,0,21,12,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,42,2022-03-14,20:00,Matchweek 29,Mon,Away,D,0.0,0.0,Crystal Palace,...,0.0,0.0,0.0,2022,Manchester City,0,0,6,20,0
29,44,2022-04-02,15:00,Matchweek 31,Sat,Away,W,2.0,0.0,Burnley,...,0.0,0.0,0.0,2022,Manchester City,1,0,4,15,5
30,46,2022-04-10,16:30,Matchweek 32,Sun,Home,D,2.0,2.0,Liverpool,...,1.0,0.0,0.0,2022,Manchester City,0,1,11,16,6
31,49,2022-04-20,20:00,Matchweek 30,Wed,Home,W,3.0,0.0,Brighton,...,0.0,0.0,0.0,2022,Manchester City,1,1,3,20,2
32,50,2022-04-23,15:00,Matchweek 34,Sat,Home,W,5.0,1.0,Watford,...,0.0,1.0,1.0,2022,Manchester City,1,1,19,15,5

In [66]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [67]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,Unnamed: 0,date,time,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
632,5,2020-10-17,17:30,Matchweek 5,Sat,Home,W,1.0,0.0,Arsenal,...,17,5,2.000000,2.333333,17.333333,4.666667,18.900000,1.333333,0.333333,0.333333
633,7,2020-10-24,12:30,Matchweek 6,Sat,Away,D,1.0,1.0,West Ham,...,12,5,1.333333,2.000000,17.333333,3.666667,17.733333,0.666667,0.000000,0.000000
634,9,2020-10-31,12:30,Matchweek 7,Sat,Away,W,1.0,0.0,Sheffield Utd,...,12,5,1.000000,0.666667,16.666667,4.333333,18.233333,0.666667,0.000000,0.000000
635,11,2020-11-08,16:30,Matchweek 8,Sun,Home,D,1.0,1.0,Liverpool,...,16,6,1.000000,0.333333,14.333333,6.666667,18.466667,1.000000,0.000000,0.000000
636,12,2020-11-21,17:30,Matchweek 9,Sat,Away,L,0.0,2.0,Tottenham,...,17,5,1.000000,0.666667,12.000000,5.666667,19.366667,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28,42,2022-03-14,20:00,Matchweek 29,Mon,Away,D,0.0,0.0,Crystal Palace,...,20,0,2.333333,1.333333,19.000000,7.000000,15.366667,0.333333,0.333333,0.333333
29,44,2022-04-02,15:00,Matchweek 31,Sat,Away,W,2.0,0.0,Burnley,...,15,5,1.666667,0.333333,18.333333,7.333333,16.000000,0.333333,0.000000,0.000000
30,46,2022-04-10,16:30,Matchweek 32,Sun,Home,D,2.0,2.0,Liverpool,...,16,6,2.000000,0.333333,20.000000,6.666667,16.133333,0.333333,0.000000,0.000000
31,49,2022-04-20,20:00,Matchweek 30,Wed,Home,W,3.0,0.0,Brighton,...,20,2,1.333333,0.666667,15.666667,4.666667,16.700000,0.333333,0.000000,0.000000
32,50,2022-04-23,15:00,Matchweek 34,Sat,Home,W,5.0,1.0,Watford,...,15,5,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000

In [68]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [69]:
matches_rolling

                             Unnamed: 0       date   time         round  day  \
team
Arsenal                 898           6 2020-10-04  14:00   Matchweek 4  Sun
                        899           7 2020-10-17  17:30   Matchweek 5  Sat
                        900           9 2020-10-25  19:15   Matchweek 6  Sun
                        901          11 2020-11-01  16:30   Matchweek 7  Sun
                        902          13 2020-11-08  19:15   Matchweek 8  Sun
...                                 ...        ...    ...           ...  ...
Wolverhampton Wanderers 227          32 2022-03-13  14:00  Matchweek 29  Sun
                        228          33 2022-03-18  20:00  Matchweek 30  Fri
                        229          34 2022-04-02  15:00  Matchweek 31  Sat
                        230          35 2022-04-08  20:00  Matchweek 32  Fri
                        231          36 2022-04-24  14:00  Matchweek 34  Sun

                            venue result   gf   ga         opponent  ...  \
team                                                                 ...
Arsenal                 898  Home      W  2.0  1.0    Sheffield Utd  ...
                        899  Away      L  0.0  1.0  Manchester City  ...
                        900  Home      L  0.0  1.0   Leicester City  ...
                        901  Away      W  1.0  0.0   Manchester Utd  ...
                        902  Home      L  0.0  3.0      Aston Villa  ...
...                           ...    ...  ...  ...              ...  ...
Wolverhampton Wanderers 227  Away      W  1.0  0.0          Everton  ...
                        228  Home      L  2.0  3.0     Leeds United  ...
                        229  Home      W  2.0  1.0      Aston Villa  ...
                        230  Away      L  0.0  1.0    Newcastle Utd  ...
                        231  Away      L  0.0  1.0          Burnley  ...

                             hour  day_code  gf_rolling  ga_rolling  \
team
Arsenal                 898    14         6    2.000000    1.333333
                        899    17         5    1.666667    1.666667
                        900    19         6    1.000000    1.666667
                        901    16         6    0.666667    1.000000
                        902    19         6    0.333333    0.666667
...                           ...       ...         ...         ...
Wolverhampton Wanderers 227    14         6    1.333333    1.000000
                        228    20         4    1.666667    0.666667
                        229    15         5    2.333333    1.000000
                        230    20         4    1.666667    1.333333
                        231    14         6    1.333333    1.666667

                            sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 898   7.666667    3.666667    14.733333   0.666667
                        899   5.333333    3.666667    15.766667   0.000000
                        900   7.000000    3.666667    16.733333   0.666667
                        901   9.666667    4.000000    16.033333   1.000000
                        902   9.666667    2.666667    18.033333   1.000000
...                                ...         ...          ...        ...
Wolverhampton Wanderers 227  12.333333    3.666667    19.300000   0.000000
                        228  12.333333    4.333333    19.600000   0.000000
                        229  13.000000    5.333333    19.833333   0.000000
                        230  13.000000    5.000000    18.533333   0.000000
                        231  10.000000    4.666667    17.633333   0.000000

                             pk_rolling  pkatt_rolling
team
Arsenal                 898    0.000000       0.000000
                        899    0.000000       0.000000
                        900    0.000000       0.000000
                        901    0.000000       0.000000
                        902    0.333333       0.333333
...                                 ...            ...
Wolverhampton Wanderers 227    0.000000       0.000000
                        228    0.000000       0.000000
                        229    0.000000       0.000000
                        230    0.000000       0.000000
                        231    0.000000       0.000000

[1317 rows x 39 columns]

In [70]:
matches_rolling = matches_rolling.droplevel('team')
matches_rolling.index = range(matches_rolling.shape[0])

In [71]:
matches_rolling

,Unnamed: 0,date,time,round,day,venue,result,gf,ga,opponent,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,6,2020-10-04,14:00,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,14,6,2.000000,1.333333,7.666667,3.666667,14.733333,0.666667,0.000000,0.000000
1,7,2020-10-17,17:30,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,17,5,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000,0.000000
2,9,2020-10-25,19:15,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,19,6,1.000000,1.666667,7.000000,3.666667,16.733333,0.666667,0.000000,0.000000
3,11,2020-11-01,16:30,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,16,6,0.666667,1.000000,9.666667,4.000000,16.033333,1.000000,0.000000,0.000000
4,13,2020-11-08,19:15,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,19,6,0.333333,0.666667,9.666667,2.666667,18.033333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,32,2022-03-13,14:00,Matchweek 29,Sun,Away,W,1.0,0.0,Everton,...,14,6,1.333333,1.000000,12.333333,3.666667,19.300000,0.000000,0.000000,0.000000
1313,33,2022-03-18,20:00,Matchweek 30,Fri,Home,L,2.0,3.0,Leeds United,...,20,4,1.666667,0.666667,12.333333,4.333333,19.600000,0.000000,0.000000,0.000000
1314,34,2022-04-02,15:00,Matchweek 31,Sat,Home,W,2.0,1.0,Aston Villa,...,15,5,2.333333,1.000000,13.000000,5.333333,19.833333,0.000000,0.000000,0.000000
1315,35,2022-04-08,20:00,Matchweek 32,Fri,Away,L,0.0,1.0,Newcastle Utd,...,20,4,1.666667,1.333333,13.000000,5.000000,18.533333,0.000000,0.000000,0.000000
1316,36,2022-04-24,14:00,Matchweek 34,Sun,Away,L,0.0,1.0,Burnley,...,14,6,1.333333,1.666667,10.000000,4.666667,17.633333,0.000000,0.000000,0.000000

In [72]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [138]:
from sklearn.metrics import precision_score
combined, error = make_predictions(matches_rolling, predictors + new_cols)
error

0.625

In [76]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [77]:
combined.head(10)

    actual  predicted       date     team        opponent result
55       0          0 2022-01-23  Arsenal         Burnley      D
56       1          0 2022-02-10  Arsenal          Wolves      W
57       1          0 2022-02-19  Arsenal       Brentford      W
58       1          1 2022-02-24  Arsenal          Wolves      W
59       1          1 2022-03-06  Arsenal         Watford      W
60       1          1 2022-03-13  Arsenal  Leicester City      W
61       0          1 2022-03-16  Arsenal       Liverpool      L
62       1          0 2022-03-19  Arsenal     Aston Villa      W
63       0          0 2022-04-04  Arsenal  Crystal Palace      L
64       0          0 2022-04-09  Arsenal        Brighton      L

In [80]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton"
              , "Manchester United": "Manchester Utd"
              , "Newcastle United": "Newcastle Utd",
              "Tottenham Hotspur": "Tottenham", 
              "West Ham United": "West Ham",
              "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [83]:
mapping["Wolverhampton Wanderers"]

'Wolves'